import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const origin='http://localhost:3000';
let keys:any;
test.beforeAll(async()=>{keys=JSON.parse(await readFile('.local/access.json','utf8'));});
async function login(page:any,role='ADMIN'){await page.goto('/admin/login');await page.getByLabel('Local access key').fill(keys.accounts.find((a:any)=>a.role===role).key);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/admin(?:\/overview)?$/);}
test('Admin publishes, visitor inquires, Sales follows up, sold disappears with history',async({page,browser})=>{
 await login(page);await page.goto('/admin/machines/new');await page.getByLabel('Manufacturer',{exact:true}).selectOption({label:'Heidelberg'});await page.getByLabel('Model',{exact:true}).fill('E2E '+Date.now());await page.getByLabel('English title',{exact:true}).fill('TEST ONLY Heidelberg E2E');await page.getByLabel('Arabic title',{exact:true}).fill('اختبار فقط Heidelberg');await page.getByLabel('Year',{exact:true}).fill('2005');await page.getByLabel('Status',{exact:true}).selectOption('AVAILABLE');await page.getByRole('button',{name:'Save machine',exact:true}).click();await expect(page).toHaveURL(/\/admin\/machines\/[a-f0-9-]+$/);const id=page.url().split('/').at(-1)!;const item=await (await page.request.get('/api/admin/machines/'+id)).json();
 const visitor=await browser.newContext();const vp=await visitor.newPage();await vp.goto(origin+'/machines?q='+encodeURIComponent(item.model));await expect(vp.getByRole('heading',{name:'TEST ONLY Heidelberg E2E'})).toBeVisible();await vp.getByRole('link',{name:'TEST ONLY Heidelberg E2E',exact:true}).click();await expect(vp.getByRole('heading',{name:'TEST ONLY Heidelberg E2E'})).toBeVisible();await vp.getByLabel('Full name').fill('E2E Customer');await vp.getByLabel('Company',{exact:false}).fill('Automated test');await vp.getByLabel('Country',{exact:false}).fill('Test');await vp.getByLabel('Email',{exact:false}).fill('e2e@example.invalid');await vp.getByLabel('WhatsApp / phone').fill('+201000000001');await vp.getByText('I agree to the processing').click();await vp.getByRole('button',{name:'Send inquiry',exact:true}).click();await expect(vp.getByRole('heading',{name:'Your inquiry has been received. Our team will follow up.'})).toBeVisible();
 const salesContext=await browser.newContext();const sp=await salesContext.newPage();await login(sp,'SALES');await sp.goto(origin+'/admin/leads');await sp.getByRole('link',{name:'E2E Customer',exact:true}).first().click();await sp.getByLabel('Lead status').selectOption('QUALIFIED');await sp.getByLabel('Internal sales note').fill('Verified through E2E');await sp.getByRole('button',{name:'Save follow-up'}).click();await expect(sp.getByText('Saved successfully.')).toBeVisible();expect((await sp.request.post(origin+'/api/admin/settings',{headers:{Origin:origin},data:{}})).status()).toBe(403);const salesMachine=await(await sp.request.get(origin+'/api/admin/machines/'+id)).json();expect(salesMachine.supplier).toBeUndefined();
 await page.goto('/admin/machines/'+id);await page.getByLabel('Status',{exact:true}).selectOption('SOLD');await page.getByRole('button',{name:'Save machine',exact:true}).click();await expect(page.getByText('Saved successfully.')).toBeVisible();const gone=await vp.goto(origin+'/machines/'+item.slug);expect(gone?.status()).toBe(410);const api=await(await vp.request.get(origin+'/api/catalog?q='+encodeURIComponent(item.model))).json();expect(api.total).toBe(0);const sitemap=await(await vp.request.get(origin+'/sitemap.xml')).text();expect(sitemap).not.toContain(item.slug);await sp.reload();await expect(sp.getByRole('heading',{name:'E2E Customer',exact:true})).toBeVisible();await visitor.close();await salesContext.close();
});
test('bilingual routes, mobile layout, redirects and access isolation',async({page})=>{for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const path of ['/','/ar','/machines','/ar/find-a-machine','/services','/blog']){await page.goto(path);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(path.startsWith('/ar'))await expect(page.locator('html')).toHaveAttribute('dir','rtl');}}const r=await page.request.get('/shop/',{maxRedirects:0});expect(r.status()).toBe(301);expect((await page.request.get('/api/admin/leads')).status()).toBe(401);await login(page,'MARKETING');expect((await page.request.get('/api/admin/leads')).status()).toBe(403);await page.goto('/admin/content');await expect(page.getByText('Page / article / service')).toBeVisible();});
