import Link from 'next/link';
import Image from 'next/image';
import {Suspense} from 'react';
import {ArrowUpRight,Globe2,Settings2,Search} from 'lucide-react';
import {words,href,type Locale} from '../../lib/i18n';
import type {Row} from '../../lib/db';
import {Consent,LanguageSwitch,TrackLink} from './public-client';
export function Shell({locale,config,local,children}:{locale:Locale;config:Row;local:boolean;children:React.ReactNode}){const w=words[locale];const links=[['machines',w.machines],['services',w.services],['find-a-machine',w.find],['sell-your-machine',w.sell],['about',w.about]];return <><a className="skip-link" href="#main">{locale==='ar'?'انتقل إلى المحتوى':'Skip to content'}</a>{local&&<div className="dev-notice">{locale==='ar'?'بيئة اختبار محلية · الرسائل محاكاة ولا تُرسل للعملاء':'Local test environment · Messages are simulated, not sent to customers'}</div>}<div className="topbar"><span>{locale==='ar'?'ماكينات الطباعة والتغليف المستعملة':'USED PRINTING & PACKAGING MACHINERY'}</span><span><Globe2 size={14}/>{locale==='ar'?'توريد عالمي':'WORLDWIDE SOURCING'}</span></div><header className="site-header"><Link href={href(locale)}><Image src="/rgm-logo.png" width={119} height={77} alt="Roza Graphic Machinery" priority/></Link><nav className="desktop-nav">{links.map(([p,t])=><Link key={p} href={href(locale,'/'+p)}>{t}</Link>)}</nav><div className="header-actions"><Suspense><LanguageSwitch locale={locale}/></Suspense><Link className="button small" href={href(locale,'/contact')}>{w.contact}<ArrowUpRight size={16}/></Link><details className="mobile-menu"><summary aria-label={locale==='ar'?'القائمة':'Menu'}>☰</summary><nav>{[...links,['blog',w.blog],['contact',w.contact]].map(([p,t])=><Link key={p} href={href(locale,'/'+p)}>{t}</Link>)}</nav></details></div></header><main id="main">{children}</main><footer className="site-footer"><div><Image src="/rgm-logo.png" width={139} height={90} alt="Roza Graphic Machinery"/><p>{locale==='ar'?'شريكك في ماكينات الطباعة المستعملة.':'Your partner in used printing machinery.'}</p></div><div><h3>{w.machines}</h3>{[['machines',w.all],['brands',w.brands],['find-a-machine',w.find],['sell-your-machine',w.sell]].map(([p,t])=><Link key={p} href={href(locale,'/'+p)}>{t}</Link>)}</div><div><h3>{locale==='ar'?'الشركة':'Company'}</h3>{[['about',w.about],['services',w.services],['blog',w.blog],['contact',w.contact],['request-inspection',w.inspection]].map(([p,t])=><Link key={p} href={href(locale,'/'+p)}>{t}</Link>)}</div><div><h3>{w.contact}</h3>{config.general_email&&<a href={'mailto:'+config.general_email}>{config.general_email}</a>}{config.primary_whatsapp&&<TrackLink event="whatsapp_click" href={'https://wa.me/'+config.primary_whatsapp.replace('+','')}>WhatsApp ↗</TrackLink>}<Link href={href(locale,'/contact')}>{w.contact}</Link><p>{config['footer_'+locale]}</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Roza Graphic Machinery</span><Link href={href(locale,'/privacy')}>{w.privacy}</Link><Link href={href(locale,'/terms')}>{w.terms}</Link></div></footer><Consent locale={locale} ids={config}/>{config.primary_whatsapp&&<TrackLink className="floating-wa" event="whatsapp_click" href={'https://wa.me/'+config.primary_whatsapp.replace('+','')}>WhatsApp ↗</TrackLink>}</>;}
export function MachineCard({m,locale}:{m:Row;locale:Locale}){const w=words[locale];const title=m['title_'+locale];const photo=m.media.find((x:Row)=>x.kind==='image');return <article className="machine-card"><Link href={href(locale,'/machines/'+m.slug)} className="card-photo">{photo?<img src={'/api/media/'+photo.id+'?w=640'} alt={title} width="640" height="440" loading="lazy"/>:<div className="no-image"><Settings2 size={40}/><span>{locale==='ar'?'الصور غير متاحة':'Photos pending'}</span></div>}<span className="badge">{m.status==='RESERVED'?w.reserved:w.available}</span></Link><div className="card-body"><p className="meta"><bdi>{m.code}</bdi></p><h3><Link href={href(locale,'/machines/'+m.slug)}>{title}</Link></h3><div className="card-specs"><span>{w.year}<strong>{m.year||'—'}</strong></span><span>{w.location}<strong>{m.location||'—'}</strong></span></div><div className="card-bottom"><span>{m.price?<bdi>{m.currency} {Number(m.price).toLocaleString(locale)}</bdi>:w.price}</span><Link href={href(locale,'/machines/'+m.slug+'#inquiry')} aria-label={w.request+': '+title}><ArrowUpRight size={21}/></Link></div></div></article>;}
export function Empty({locale}:{locale:Locale}){const w=words[locale];return <div className="empty-state"><Search size={36}/><h3>{w.empty}</h3><p>{w.emptyHelp}</p><Link className="button" href={href(locale,'/find-a-machine')}>{w.find}<ArrowUpRight size={18}/></Link></div>;}
export function Title({title,subtitle}:{title:string;subtitle?:string}){return <div className="page-heading"><p className="eyebrow">ROZA GRAPHIC MACHINERY</p><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>;}
