'use client';
import {useState,useRef,useEffect} from 'react';
import {usePathname,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {words,type Locale,href} from '../../lib/i18n';
export function LanguageSwitch({locale}:{locale:Locale}){const path=usePathname();const params=useSearchParams();const other=locale==='ar'?path.replace(/^\/ar(?=\/|$)/,'')||'/':`/ar${path==='/'?'':path}`;return <Link href={other+(params.size?'?'+params.toString():'')} lang={locale==='ar'?'en':'ar'} className="language">{locale==='ar'?'EN':'العربية'}</Link>;}
export function track(event:string,machine_id?:string){if(localStorage.getItem('rgm-consent')!=='accepted')return;fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,machine_id}),keepalive:true}).catch(()=>{});const w=window as any;w.dataLayer?.push({event,machine_id});}
export function Consent({locale,ids}:{locale:Locale;ids:{ga_id?:string;gtm_id?:string;meta_pixel_id?:string}}){const [choice,setChoice]=useState<string|null>(null);useEffect(()=>{setChoice(localStorage.getItem('rgm-consent'));},[]);useEffect(()=>{if(choice!=='accepted')return;const w=window as any;w.dataLayer=w.dataLayer||[];if(/^G-[A-Z0-9]+$/.test(ids.ga_id||'')){const s=document.createElement('script');s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${ids.ga_id}`;document.head.appendChild(s);w.gtag=function(...args:any[]){w.dataLayer.push(args);};w.gtag('js',new Date());w.gtag('config',ids.ga_id,{send_page_view:true});}else if(/^GTM-[A-Z0-9]+$/.test(ids.gtm_id||'')){w.dataLayer.push({'gtm.start':Date.now(),event:'gtm.js'});const s=document.createElement('script');s.src=`https://www.googletagmanager.com/gtm.js?id=${ids.gtm_id}`;document.head.appendChild(s);}},[choice,ids.ga_id,ids.gtm_id]);function choose(v:string){localStorage.setItem('rgm-consent',v);setChoice(v);if(v==='rejected')location.reload();}return <>{choice===null&&<aside className="cookie" aria-label={locale==='ar'?'إعدادات الخصوصية':'Privacy settings'}><p>{locale==='ar'?'نستخدم أدوات قياس اختيارية لتحسين الموقع، بعد موافقتك فقط.':'Optional analytics help us improve the website. They load only with your consent.'}</p><button onClick={()=>choose('accepted')}>{locale==='ar'?'موافقة':'Accept'}</button><button className="secondary" onClick={()=>choose('rejected')}>{locale==='ar'?'رفض':'Reject'}</button></aside>}<button className="cookie-settings" onClick={()=>setChoice(null)}>{locale==='ar'?'إعدادات الخصوصية':'Privacy settings'}</button></>;}
const detailLabels:Record<string,[string,string]>={manufacturer:['Manufacturer','الشركة المصنعة'],model:['Model','الطراز'],category:['Category','الفئة'],year_from:['Year from','من سنة'],year_to:['Year to','إلى سنة'],colors:['Colors','عدد الألوان'],sheet_size:['Sheet size','مقاس الورق'],coating:['Coating','وحدة الورنيش'],perfecting:['Perfecting','الطباعة على الوجهين'],budget:['Budget','الميزانية'],currency:['Currency','العملة'],region:['Preferred region','المنطقة المفضلة'],destination:['Destination country','دولة الوجهة'],year:['Year','سنة الصنع'],serial:['Serial number','الرقم التسلسلي'],counter:['Impressions / counter','عداد الطبعات'],location:['Machine location','موقع الماكينة'],condition:['Condition','الحالة'],expected_price:['Expected price','السعر المتوقع'],timeframe:['Requested timeframe','الموعد المطلوب'],seller:['Seller information','معلومات البائع'],requirements:['Technical requirements','المتطلبات الفنية'],video:['Video URL','رابط الفيديو']};
export function InquiryForm({locale,type,machineId,service}:{locale:Locale;type:string;machineId?:string;service?:string}){const w=words[locale];const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[uploadError,setUploadError]=useState('');const key=useRef('');const receipt=useRef<{id:string;upload_token?:string}|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const details=type==='MACHINE_WANTED'?['category','manufacturer','model','year_from','year_to','colors','sheet_size','coating','perfecting','budget','currency','region','destination','requirements']:type==='SELL_MACHINE'?['manufacturer','model','year','serial','counter','location','condition','expected_price','currency','video']:type==='INSPECTION_REQUEST'?['manufacturer','model','year','location','seller','timeframe','destination']:[];
 async function upload(){if(!receipt.current?.upload_token||!fileRef.current?.files?.length)return;for(const file of Array.from(fileRef.current.files)){const f=new FormData();f.set('file',file);f.set('token',receipt.current.upload_token);const r=await fetch('/api/uploads',{method:'POST',body:f});if(!r.ok)throw new Error((await r.json()).error);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);if(!key.current)key.current=crypto.randomUUID();const detail:Record<string,string>={};for(const d of details){const v=String(f.get(d)||'');if(v)detail[d]=v;}if(service)detail.service=service;const p=new URLSearchParams(location.search);const attribution:Record<string,string>={landing_page:location.pathname,referrer:document.referrer};for(const x of ['utm_source','utm_medium','utm_campaign'])if(p.get(x))attribution[x]=p.get(x)!;
 try{if(!receipt.current){const body={type,machine_id:machineId,language:locale,idempotency_key:key.current,name:f.get('name'),company:f.get('company'),country:f.get('country'),email:f.get('email'),phone:f.get('phone'),message:f.get('message'),website:f.get('website')||'',privacy_consent:f.get('privacy')==='on',whatsapp_consent:f.get('whatsapp')==='on',detail,attribution};const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await r.json();if(!r.ok)throw new Error(json.fields?json.fields.map((x:any)=>`${x.path}: ${x.message}`).join(' · '):json.error);receipt.current=json;track(type==='MACHINE_INQUIRY'?'machine_inquiry_submit':type==='MACHINE_WANTED'?'machine_wanted_submit':type==='SELL_MACHINE'?'sell_machine_submit':type==='INSPECTION_REQUEST'?'inspection_request_submit':'service_inquiry_submit',machineId);}try{await upload();}catch(err){setUploadError((locale==='ar'?'تم حفظ الاستفسار، لكن تعذر رفع بعض الملفات: ':'Inquiry saved, but some attachments failed: ')+(err as Error).message);}setSuccess(true);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 if(success)return <div className="success" role="status"><h3>{w.success}</h3><p><bdi>{receipt.current?.id}</bdi></p>{uploadError&&<><p className="error">{uploadError}</p><button onClick={async()=>{try{await upload();setUploadError('');}catch{}}}>{locale==='ar'?'إعادة رفع الملفات':'Retry attachments'}</button></>}</div>;
 return <form className="inquiry-form" onSubmit={submit} onFocus={()=>{if(!key.current){key.current=crypto.randomUUID();track('machine_inquiry_start',machineId);}}}><div className="form-grid">{details.map(d=><label key={d}>{detailLabels[d][locale==='ar'?1:0]}{d==='model'&&['SELL_MACHINE','INSPECTION_REQUEST'].includes(type)?' *':''}<input name={d} required={d==='model'&&['SELL_MACHINE','INSPECTION_REQUEST'].includes(type)} maxLength={d==='requirements'?5000:300} type={['year_from','year_to','year','budget','expected_price'].includes(d)?'number':'text'} min="0" step={['budget','expected_price'].includes(d)?'0.01':undefined}/></label>)}{['name','company','country','email','phone'].map(d=><label key={d}>{w[d as keyof typeof w]}{d!=='company'?' *':''}<input name={d} type={d==='email'?'email':d==='phone'?'tel':'text'} required={d!=='company'} maxLength={d==='email'?254:160} placeholder={d==='phone'?'+201234567890':undefined} dir={d==='phone'||d==='email'?'ltr':undefined} pattern={d==='phone'?'\+[1-9][0-9]{7,14}':undefined}/></label>)}</div><label>{w.message}<textarea name="message" rows={4} maxLength={5000}/></label>{['SELL_MACHINE','INSPECTION_REQUEST'].includes(type)&&<label>{w.files}<input ref={fileRef} type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf"/><small>JPEG / PNG / WebP / PDF · 10 MB</small></label>}<div className="honeypot" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div><label className="check"><input type="checkbox" name="privacy" required/>{w.consent} *</label><label className="check"><input type="checkbox" name="whatsapp"/>{w.waConsent}</label>{error&&<p className="error" role="alert">{error}</p>}<button type="submit" disabled={busy}>{busy?w.saving:w.submit}</button></form>;
}
export function Gallery({media,title,locale}:{media:any[];title:string;locale:Locale}){const [selected,setSelected]=useState(0);const dialog=useRef<HTMLDialogElement>(null);const images=media.filter(m=>m.kind==='image');if(!images.length)return <div className="no-image">{locale==='ar'?'الصور غير متاحة بعد':'Images not yet available'}</div>;return <div className="gallery"><button className="gallery-main" onClick={()=>dialog.current?.showModal()} aria-label={locale==='ar'?'تكبير الصورة':'Enlarge image'}><img src={`/api/media/${images[selected].id}?w=1200`} alt={images[selected][`alt_${locale}`]||title} width="1000" height="700"/></button><div className="thumbs">{images.map((m,i)=><button key={m.id} aria-pressed={selected===i} onClick={()=>setSelected(i)}><img src={`/api/media/${m.id}?w=150`} alt={`${title} ${i+1}`} width="88" height="66" loading="lazy"/></button>)}</div><dialog ref={dialog} className="lightbox"><button onClick={()=>dialog.current?.close()}>{locale==='ar'?'إغلاق':'Close'} ×</button><img src={`/api/media/${images[selected].id}?w=2400`} alt={title}/></dialog></div>;}
export function TrackLink({event,href:to,children,machineId,className}:{event:string;href:string;children:React.ReactNode;machineId?:string;className?:string}){return <a className={className} href={to} onClick={()=>track(event,machineId)}>{children}</a>;}
