import nodemailer from 'nodemailer';
import type {DB,Row} from './db';
import {settings,catalog} from './repository';
const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export interface EmailProvider{send(to:string,subject:string,html:string,text:string,key:string):Promise<string>;}
export interface WhatsAppProvider{send(to:string,template:string,language:string,parameters:string[],key:string):Promise<string>;}
function allowSend(to:string){if(process.env.APP_ENV==='production')return;const allowed=(process.env.TEST_RECIPIENT_ALLOWLIST||'').split(',').map(s=>s.trim());if(!allowed.includes(to))throw new Error('TEST_RECIPIENT_NOT_ALLOWED');}
export const emailProvider:EmailProvider={async send(to,subject,html,text,key){const provider=process.env.EMAIL_PROVIDER||'mock';if(provider==='mock')return `mock-${key}`;allowSend(to);
 if(provider==='smtp'){if(!process.env.EMAIL_HOST||!process.env.EMAIL_FROM)throw new Error('CONFIGURATION_REQUIRED');const transporter=nodemailer.createTransport({host:process.env.EMAIL_HOST,port:Number(process.env.EMAIL_PORT||587),secure:process.env.EMAIL_PORT==='465',requireTLS:true,auth:{user:process.env.EMAIL_USER,pass:process.env.EMAIL_PASSWORD},connectionTimeout:10000,socketTimeout:20000});const info=await transporter.sendMail({from:process.env.EMAIL_FROM,replyTo:process.env.EMAIL_REPLY_TO,to,subject,html,text,messageId:`<${key}@${new URL(process.env.NEXT_PUBLIC_SITE_URL!).hostname}>`});return info.messageId;}
 if(provider==='resend'){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.EMAIL_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[to],subject,html,text,reply_to:process.env.EMAIL_REPLY_TO}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`PROVIDER_HTTP_${r.status}`);return (await r.json()).id;}
 if(provider==='postmark'){const r=await fetch('https://api.postmarkapp.com/email',{method:'POST',headers:{'X-Postmark-Server-Token':process.env.EMAIL_API_KEY||'','Content-Type':'application/json'},body:JSON.stringify({From:process.env.EMAIL_FROM,To:to,Subject:subject,HtmlBody:html,TextBody:text,ReplyTo:process.env.EMAIL_REPLY_TO,Metadata:{key}}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`PROVIDER_HTTP_${r.status}`);return (await r.json()).MessageID;}
 throw new Error('CONFIGURATION_REQUIRED');}};
export const whatsappProvider:WhatsAppProvider={async send(to,template,language,parameters,key){const provider=process.env.WHATSAPP_PROVIDER||'mock';if(provider==='mock')return `mock-${key}`;allowSend(to);if(provider==='meta'){if(!process.env.META_GRAPH_VERSION||!process.env.WHATSAPP_PHONE_ID)throw new Error('CONFIGURATION_REQUIRED');const r=await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION}/${process.env.WHATSAPP_PHONE_ID}/messages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WHATSAPP_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:to.replace('+',''),type:'template',template:{name:template,language:{code:language},components:[{type:'body',parameters:parameters.map(text=>({type:'text',text}))}]}}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`PROVIDER_HTTP_${r.status}`);return (await r.json()).messages[0].id;}
 if(provider==='wati'){const base=process.env.WATI_API_URL;if(!base?.startsWith('https://'))throw new Error('CONFIGURATION_REQUIRED');const r=await fetch(`${base.replace(/\/$/,'')}/api/v1/sendTemplateMessage?whatsappNumber=${encodeURIComponent(to.replace('+',''))}`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WHATSAPP_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({template_name:template,broadcast_name:`rgm-${key}`,parameters:parameters.map((value,i)=>({name:String(i+1),value}))}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`PROVIDER_HTTP_${r.status}`);const result=await r.json();if(result.result===false)throw new Error('PROVIDER_REJECTED');return result.messageId||key;}throw new Error('CONFIGURATION_REQUIRED');}};
export async function renderEmail(db:DB,lead:Row,internal=false){const ar=lead.language==='ar';const config=await settings(db);let machine:Row|undefined;if(lead.machine_id){machine=(await catalog(db,{},lead.machine_id)).items[0];if(machine){const {rows}=await db.query('SELECT selling_price::text,currency,send_email_price FROM machine_commercial WHERE machine_id=$1',[lead.machine_id]);machine={...machine,price:internal||rows[0].send_email_price?rows[0].selling_price:null,currency:rows[0].currency};}}
 const title=machine?.[ar?'title_ar':'title_en']||lead.snapshot[ar?'title_ar':'title_en']|| (ar?'استفسارك لدى RGM':'Your RGM inquiry');
 const base=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';const url=machine?`${base}${ar?'/ar':''}/machines/${machine.slug}`:`${base}${ar?'/ar':''}/machines`;
 const intro=ar?'شكراً لتواصلك مع روزا جرافيك ماشينري. تم استلام طلبك وسيتواصل معك فريقنا.':'Thank you for contacting Roza Graphic Machinery. Your request has been received and our team will follow up.';
 const offer=machine?.price?`${machine.currency} ${machine.price}`:ar?'سيتواصل معك فريق المبيعات لتقديم العرض التجاري الحالي.':'Our sales team will contact you shortly with the current commercial offer.';
 const lines=[internal?'New lead / استفسار جديد':intro,title,machine?.code||'',machine?.year||'',machine?.location||'',offer,...(internal?[lead.name,lead.company,lead.country,lead.email,lead.phone,lead.message,`${base}/admin/leads/${lead.id}`]:[])];
 const html=`<html lang="${ar?'ar':'en'}" dir="${ar?'rtl':'ltr'}"><body style="font-family:Arial,sans-serif;color:#182765"><img src="${base}/rgm-logo.png" width="150" alt="Roza Graphic Machinery"/><h1>${escape(title)}</h1>${lines.map(l=>`<p>${escape(l)}</p>`).join('')}${machine?.media?.[0]?`<img src="${base}/api/media/${machine.media[0].id}" width="480" alt="${escape(title)}"/>`:''}<a href="${escape(url)}">${ar?'عرض الماكينات':'View machinery'}</a><p>${escape(config.general_email)}</p></body></html>`;
 return {subject:`${internal?'New lead':'RGM'} — ${title}`,html,text:lines.join('\n')+'\n'+url};
}
export async function processOutbox(db:DB,limit=20){
 // Expired leases are ambiguous: never blindly repeat a potentially accepted send.
 await db.query("UPDATE outbox SET status='UNKNOWN',error='Lease expired; verify provider before retry',updated_at=now() WHERE status='PROCESSING' AND lease_until<now()");
 const results=[];
 for(let i=0;i<limit;i++){
 const job=await db.transaction(async tx=>{const {rows}=await tx.query("SELECT * FROM outbox WHERE status='PENDING' AND next_attempt<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1");if(!rows[0])return null;await tx.query("UPDATE outbox SET status='PROCESSING',attempts=attempts+1,lease_until=now()+interval '2 minutes',updated_at=now() WHERE id=$1",[rows[0].id]);return rows[0];});if(!job)break;
 let status='SENT',error:string|null=null,providerId:string|null=null;const provider=job.kind==='WHATSAPP'?(process.env.WHATSAPP_PROVIDER||'mock'):(process.env.EMAIL_PROVIDER||'mock');
 try{const lead=(await db.query('SELECT * FROM leads WHERE id=$1',[job.lead_id])).rows[0];const config=await settings(db);
 if(job.kind==='WHATSAPP'){if(!config.whatsapp_enabled||!lead.whatsapp_consent){status='SKIPPED';}else{const template=lead.language==='ar'?config.whatsapp_template_ar:config.whatsapp_template_en;if(!template&&provider!=='mock')throw new Error('CONFIGURATION_REQUIRED');providerId=await whatsappProvider.send(lead.phone,template||'mock_inquiry',lead.language,[lead.name,lead.snapshot.code||lead.type,`${process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000'}/${lead.language==='ar'?'ar/':''}machines`],job.id);}}
 else{const to=job.kind==='CUSTOMER_EMAIL'?lead.email:(lead.type==='SERVICE_INQUIRY'?config.service_email||config.inquiry_email:config.inquiry_email);if(!to&&provider!=='mock')throw new Error('CONFIGURATION_REQUIRED');const msg=await renderEmail(db,lead,job.kind==='INTERNAL_EMAIL');providerId=await emailProvider.send(to||'unconfigured@example.invalid',msg.subject,msg.html,msg.text,job.id);}
 if(provider==='mock'&&status==='SENT')status='SIMULATED';
 }catch(e){error=e instanceof Error?e.message:'PROVIDER_ERROR';if(error.includes('CONFIGURATION')||error.includes('NOT_ALLOWED'))status='CONFIGURATION_REQUIRED';else if(/^PROVIDER_HTTP_(429|5\d\d)$/.test(error))status=job.attempts<4?'PENDING':'FAILED';else if(error.startsWith('PROVIDER_HTTP_')||error==='PROVIDER_REJECTED')status='FAILED';else{status='UNKNOWN';error='Delivery outcome unknown; reconcile provider before retry';}}
 await db.transaction(async tx=>{await tx.query("UPDATE outbox SET status=$2,provider_id=$3,error=$4,lease_until=NULL,next_attempt=now()+interval '5 minutes',updated_at=now() WHERE id=$1",[job.id,status,providerId,error]);await tx.query('INSERT INTO delivery_attempts(outbox_id,provider,status,error) VALUES($1,$2,$3,$4)',[job.id,provider,status,error]);});results.push({id:job.id,status});
 }return results;
}
