import ExcelJS from 'exceljs';
import {parse} from 'csv-parse/sync';
import {createHash} from 'node:crypto';
import {machineSchema} from './validation';
import {AppError,saveMachine,audit} from './repository';
import type {DB} from './db';
export const importHeaders=['Manufacturer','Model','Year','Machine Name','Arabic Name','Category','Subcategory','Colors','Sheet Width mm','Sheet Height mm','Impressions','Serial Number','Condition','Location','Selling Price','Currency','English Description','Arabic Description','Configuration','Video URL'];
function checkZip(buffer:Buffer){let total=0,entries=0;for(let i=0;i<buffer.length-46;i++){if(buffer.readUInt32LE(i)!==0x02014b50)continue;const size=buffer.readUInt32LE(i+24),flags=buffer.readUInt16LE(i+8),nameLength=buffer.readUInt16LE(i+28);if(size===0xffffffff||flags&1)throw new AppError('Encrypted/ZIP64 workbooks are not supported.');total+=size;entries++;const name=buffer.subarray(i+46,i+46+nameLength).toString();if(/vbaProject|externalLinks/i.test(name))throw new AppError('Macros and external links are not supported.');if(total>40_000_000||entries>2000)throw new AppError('Workbook expands beyond the safe size limit.');}if(!entries)throw new AppError('Invalid XLSX archive.');}
export async function parseImport(buffer:Buffer,filename:string){if(buffer.length>10_000_000)throw new AppError('Maximum file size is 10 MB.');let rows:Record<string,string>[]=[];
 if(filename.toLowerCase().endsWith('.csv')){rows=parse(buffer,{columns:true,bom:true,skip_empty_lines:true,max_record_size:100000,relax_column_count:false});}
 else if(filename.toLowerCase().endsWith('.xlsx')){checkZip(buffer);const book=new ExcelJS.Workbook();await book.xlsx.load(buffer as any);const sheet=book.worksheets[0];if(!sheet||sheet.rowCount>1001)throw new AppError('Maximum 1,000 rows.');const headers=(sheet.getRow(1).values as any[]).slice(1).map(String);sheet.eachRow((row,index)=>{if(index===1)return;const record:Record<string,string>={};headers.forEach((h,i)=>{const cell=row.getCell(i+1);if(cell.type===ExcelJS.ValueType.Formula)throw new AppError(`Row ${index}: formulas are not allowed.`);record[h]=cell.text;});rows.push(record);});}else throw new AppError('Upload a CSV or XLSX file.');
 if(rows.length>1000||!rows.length)throw new AppError('Upload between 1 and 1,000 rows.');
 return rows.map((r,i)=>{const errors:string[]=[];if(Object.keys(r).some(k=>/machine.?code/i.test(k)))errors.push('Machine codes are generated automatically; remove this column.');if(Object.values(r).some(v=>String(v).length>32000||/^[=]/.test(String(v))))errors.push('Formula or oversized cell.');
 const m={manufacturer:r.Manufacturer,model:r.Model,title_en:r['Machine Name']||`${r.Manufacturer||''} ${r.Model||''}`,title_ar:r['Arabic Name']||`${r.Manufacturer||''} ${r.Model||''}`,year:r.Year?Number(r.Year):null,category:r.Category,subcategory:r.Subcategory||'',location:r.Location||'',condition:r.Condition||'',description_en:r['English Description']||'',description_ar:r['Arabic Description']||'',configuration_en:r.Configuration||'',configuration_ar:'',serial:r['Serial Number']||'',selling_price:r['Selling Price']||'',currency:r.Currency||'EUR',status:'DRAFT',specs:{...(r.Colors?{colors:Number(r.Colors)}:{}),...(r['Sheet Width mm']?{width_mm:Number(r['Sheet Width mm'])}:{}),...(r['Sheet Height mm']?{height_mm:Number(r['Sheet Height mm'])}:{}),...(r.Impressions?{impressions:Number(r.Impressions)}:{}),...(r['Video URL']?{video:r['Video URL']}:{})}};
 const result=machineSchema.safeParse(m);if(!result.success)errors.push(...result.error.issues.map(e=>`${e.path.join('.')}: ${e.message}`));return {row:i+2,data:result.success?result.data:m,errors};});
}
export async function previewImport(db:DB,buffer:Buffer,filename:string,actor:string){const rows=await parseImport(buffer,filename);const tax=(await db.query('SELECT kind,slug,name_en FROM taxonomy WHERE active=true')).rows;for(const row of rows){if(!tax.some(t=>t.kind==='category'&&t.slug===row.data.category))row.errors.push('Category must match an active category slug.');if(!tax.some(t=>t.kind==='manufacturer'&&t.name_en===row.data.manufacturer))row.errors.push('Manufacturer must match an active manufacturer.');}const result=await db.query('INSERT INTO imports(actor,checksum,rows) VALUES($1,$2,$3) RETURNING id',[actor,createHash('sha256').update(buffer).digest('hex'),JSON.stringify(rows)]);return {id:result.rows[0].id,rows};}
export async function commitImport(db:DB,id:string,actor:string){return db.transaction(async tx=>{const batch=(await tx.query('SELECT * FROM imports WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!batch)throw new AppError('Import not found',404);if(batch.committed)return batch.result;const results=[];for(const row of batch.rows){if(row.errors.length)continue;
 // saveMachine uses transaction; reuse the active transaction rather than nesting BEGIN.
 const nested={...tx,transaction:async<T>(fn:(db:DB)=>Promise<T>)=>fn(tx)};results.push(await saveMachine(nested,row.data,actor));}
 await tx.query('UPDATE imports SET committed=true,result=$2 WHERE id=$1',[id,JSON.stringify(results)]);await audit(tx,actor,'import.committed',id);return results;});}
