import {readFile} from 'node:fs/promises';
import sanitize from 'sanitize-html';
import type {DB} from './db';
export async function seed(db:DB){
 const categories=[['sheetfed-offset','Sheetfed Offset','طباعة أوفست ورقية'],['web-offset','Web Offset','أوفست رول'],['digital','Digital Printing','طباعة رقمية'],['flexographic','Flexographic','طباعة فلكسو'],['prepress','Prepress','ما قبل الطباعة'],['cutting','Cutting','قص الورق'],['folding','Folding','طي الورق'],['die-cutting','Die Cutting','التكسير والقص بالقوالب'],['binding','Binding','تجليد'],['folder-gluing','Folder Gluing','طي ولصق'],['packaging','Packaging','تغليف'],['laminating','Laminating','تغليف حراري'],['other','Other Machinery','ماكينات أخرى']];
 for(const [slug,en,ar] of categories)await db.query("INSERT INTO taxonomy(kind,slug,name_en,name_ar) VALUES('category',$1,$2,$3) ON CONFLICT DO NOTHING",[slug,en,ar]);
 // Manufacturer vocabulary is sourced from the existing company site; no stock is seeded.
 for(const name of ['Heidelberg','Roland','KBA'])await db.query("INSERT INTO taxonomy(kind,slug,name_en,name_ar) VALUES('manufacturer',$1,$2,$2) ON CONFLICT DO NOTHING",[name.toLowerCase(),name]);
 const documents=[
 ['home','page','Used printing machinery. Sourced globally.','ماكينات طباعة مستعملة. نبحث عنها حول العالم.','Buy, sell and source used printing, packaging and finishing machinery with RGM’s technical and commercial support.','شراء وبيع وتوريد ماكينات الطباعة والتغليف والتجهيز النهائي المستعملة، بدعم فني وتجاري من RGM.'],
 ['about','page','Machinery expertise. International reach.','خبرة في الماكينات. وتواصل حول العالم.','Roza Graphic Machinery trades used printing machinery and supports customers with installation, maintenance, dismantling, relocation, packing and shipment. Our work combines machinery sourcing with technical and commercial support. Contact RGM to discuss your machine requirements and destination.','تعمل روزا جرافيك ماشينري في تجارة ماكينات الطباعة المستعملة، وتدعم العملاء في التركيب والصيانة والفك والنقل والتعبئة والشحن. نجمع بين توريد الماكينات والدعم الفني والتجاري. تواصل مع RGM لمناقشة احتياجاتك ووجهة الشحن.'],
 ['cylinder-repair','service','Cylinder repair','إصلاح السلندرات','RGM offers cylinder repair for printing machinery. Contact the technical team with the machine model, cylinder condition and photographs to discuss the scope of work.','تقدم RGM خدمة إصلاح سلندرات ماكينات الطباعة. أرسل إلى الفريق الفني طراز الماكينة وحالة السلندر وصوراً له لمناقشة نطاق العمل المطلوب.'],
 ['installation-maintenance','service','Installation & maintenance','التركيب والصيانة','Technical support for installing and maintaining printing machinery. Describe your machine, location and support requirements so RGM can assess the work.','دعم فني لتركيب ماكينات الطباعة وصيانتها. أرسل بيانات الماكينة وموقعها ونوع الدعم المطلوب ليتولى فريق RGM دراسة العمل.'],
 ['packing-shipping','service','Packing & shipping','التعبئة والشحن','Packing and shipment support for printing machinery. Contact RGM with the machine details, collection location and destination to discuss arrangements.','دعم لتعبئة ماكينات الطباعة وشحنها. تواصل مع RGM وأرسل تفاصيل الماكينة وموقع الاستلام والوجهة لمناقشة الترتيبات.'],
 ['dismantling-relocation','service','Dismantling & relocation','الفك والنقل','RGM supports machinery dismantling and relocation logistics. Share your equipment and site requirements to discuss a suitable plan.','تدعم RGM أعمال فك الماكينات وترتيبات نقلها. أرسل بيانات المعدات ومتطلبات الموقع لمناقشة خطة مناسبة.'],
 ['after-sales','service','After-sales support','خدمات ما بعد البيع','After-sales support includes assistance with machine installation, operation training and maintenance. Contact the team to confirm the support appropriate to your equipment.','تشمل خدمات ما بعد البيع المساعدة في تركيب الماكينات والتدريب على تشغيلها وصيانتها. تواصل مع الفريق لتحديد الدعم المناسب لمعداتك.']
 ];
 for(const [slug,kind,en,ar,bodyEn,bodyAr] of documents)await db.query('INSERT INTO content(slug,kind,title_en,title_ar,body_en,body_ar,published,arabic_ready,source_url) VALUES($1,$2,$3,$4,$5,$6,true,true,$7) ON CONFLICT DO NOTHING',[slug,kind,en,ar,bodyEn,bodyAr,kind==='service'?'https://rgmachinery.com/service/':'https://rgmachinery.com/about-used-offset-priniting-machine/']);
 const posts=JSON.parse(await readFile('migration/source/posts.json','utf8'));
 for(const post of posts){const body=sanitize(post.content.rendered.replace(/\[\/?et_[^\]]*\]/g,''),{allowedTags:['h2','h3','h4','p','br','strong','em','ul','ol','li','blockquote','a','img'],allowedAttributes:{a:['href'],img:['src','alt']},allowedSchemes:['https','http'],transformTags:{a:(_tag,attrs)=>({tagName:'a',attribs:{...attrs,rel:'noopener noreferrer'}})}});await db.query("INSERT INTO content(slug,kind,title_en,title_ar,body_en,body_ar,published,arabic_ready,source_url,original_date) VALUES($1,'article',$2,$2,$3,'',true,false,$4,$5) ON CONFLICT DO NOTHING",[post.slug,sanitize(post.title.rendered,{allowedTags:[]}),body,post.link,post.date_gmt+'Z']);}
 for(const [source,dest] of [['/shop/','/machines'],['/service/','/services'],['/contact-us/','/contact'],['/about-used-offset-priniting-machine/','/about']])await db.query('INSERT INTO redirects(source,destination) VALUES($1,$2) ON CONFLICT DO NOTHING',[source,dest]);
}
