import {z} from 'zod';
export const machineStatuses=['DRAFT','AVAILABLE','RESERVED','SOLD','ARCHIVED'] as const;
export const leadStatuses=['NEW','CONTACTED','QUALIFIED','OFFER_SENT','NEGOTIATION','WON','LOST','SPAM'] as const;
export const leadTypes=['MACHINE_INQUIRY','MACHINE_WANTED','SELL_MACHINE','INSPECTION_REQUEST','SERVICE_INQUIRY','GENERAL_CONTACT'] as const;
const text=(n=200)=>z.string().trim().max(n);
const required=(n=200)=>text(n).min(1);
const money=z.union([z.literal(''),z.string().regex(/^\d{1,14}(\.\d{1,2})?$/)]).default('');
export const machineSchema=z.object({
 status:z.enum(machineStatuses).default('DRAFT'), manufacturer:required(),model:required(),category:required(),subcategory:text().default(''),
 year:z.coerce.number().int().min(1850).max(new Date().getFullYear()+1).nullable().default(null),
 title_en:required(300),title_ar:required(300),description_en:text(20000).default(''),description_ar:text(20000).default(''),
 location:text().default(''),condition:text().default(''),configuration_en:text(10000).default(''),configuration_ar:text(10000).default(''),seo_en:text(300).default(''),seo_ar:text(300).default(''),
 specs:z.object({colors:z.coerce.number().int().min(1).max(20).optional(),width_mm:z.coerce.number().positive().optional(),height_mm:z.coerce.number().positive().optional(),impressions:z.coerce.number().nonnegative().optional(),hours:z.coerce.number().nonnegative().optional(),perfecting:text().optional(),coating:text().optional(),video:z.union([z.literal(''),z.url().refine(u=>['www.youtube.com','youtube.com','youtu.be','vimeo.com','www.vimeo.com'].includes(new URL(u).hostname))]).optional(),additional:text(5000).optional()}).default({}),
 selling_price:money,currency:z.string().regex(/^[A-Z]{3}$/).default('EUR'),show_public_price:z.boolean().default(false),send_email_price:z.boolean().default(false),
 supplier:text().default(''),supplier_contact:text().default(''),purchase_price:money,cost:money,commission:money,notes:text(10000).default(''),serial:text().default(''),source_url:text(2000).default(''),version:z.number().int().positive().optional(),
}).superRefine((m,ctx)=>{if(m.category!=='sheetfed-offset'&&m.specs.colors)ctx.addIssue({code:'custom',path:['specs','colors'],message:'Colors are only applicable to sheetfed offset.'});if((m.show_public_price||m.send_email_price)&&!m.selling_price)ctx.addIssue({code:'custom',path:['selling_price'],message:'Set a selling price before enabling price disclosure.'});});
export const leadSchema=z.object({
 type:z.enum(leadTypes),name:required(120),company:text(160).default(''),country:required(100),email:z.email().max(254),phone:z.string().regex(/^\+[1-9]\d{7,14}$/),language:z.enum(['en','ar']),message:text(5000).default(''),machine_id:z.uuid().optional(),privacy_consent:z.literal(true),whatsapp_consent:z.boolean().default(false),idempotency_key:z.uuid(),website:z.literal('').default(''),
 detail:z.object({manufacturer:text().optional(),model:text().optional(),category:text().optional(),year_from:z.coerce.number().int().min(1850).max(2200).optional(),year_to:z.coerce.number().int().min(1850).max(2200).optional(),colors:text(30).optional(),sheet_size:text(100).optional(),coating:text().optional(),perfecting:text().optional(),budget:money.optional(),currency:text(3).optional(),region:text().optional(),destination:text().optional(),year:text(4).optional(),serial:text().optional(),counter:text().optional(),location:text().optional(),condition:text().optional(),expected_price:money.optional(),timeframe:text().optional(),seller:text(1000).optional(),service:text().optional(),video:text(2000).optional(),requirements:text(5000).optional()}).default({}),
 attribution:z.object({utm_source:text(200).optional(),utm_medium:text(200).optional(),utm_campaign:text(200).optional(),referrer:text(1000).optional(),landing_page:text(1000).optional()}).default({})
}).superRefine((l,ctx)=>{if(l.type==='MACHINE_INQUIRY'&&!l.machine_id)ctx.addIssue({code:'custom',path:['machine_id'],message:'Machine required'});if(l.type==='SERVICE_INQUIRY'&&!l.detail.service)ctx.addIssue({code:'custom',path:['detail','service'],message:'Service required'});if(['SELL_MACHINE','INSPECTION_REQUEST'].includes(l.type)&&!l.detail.model)ctx.addIssue({code:'custom',path:['detail','model'],message:'Model required'});if(l.detail.year_from&&l.detail.year_to&&l.detail.year_from>l.detail.year_to)ctx.addIssue({code:'custom',path:['detail','year_to'],message:'Invalid year range'});});
export type MachineInput=z.infer<typeof machineSchema>;
export type LeadInput=z.infer<typeof leadSchema>;
export const settingsSchema=z.object({company_name:z.literal('Roza Graphic Machinery').default('Roza Graphic Machinery'),primary_whatsapp:z.union([z.literal(''),z.string().regex(/^\+[1-9]\d{7,14}$/)]).default(''),phone:text().default(''),general_email:z.union([z.literal(''),z.email()]).default(''),inquiry_email:z.union([z.literal(''),z.email()]).default(''),service_email:z.union([z.literal(''),z.email()]).default(''),include_reserved:z.boolean().default(false),whatsapp_enabled:z.boolean().default(false),whatsapp_template_en:text().default(''),whatsapp_template_ar:text().default(''),countries:z.array(z.object({country:required(),label:required(),address:text(1000),phone:text(),email:text()})).max(10).default([]),social_links:z.array(z.url().refine(u=>u.startsWith('https://'))).max(10).default([]),ga_id:text(30).default(''),gtm_id:text(30).default(''),meta_pixel_id:text(30).default(''),footer_en:text(500).default(''),footer_ar:text(500).default('')});
