import {z} from 'zod';
import {getDB} from '../../../../lib/db';
import {requireStaff} from '../../../../lib/auth';
import {settings,audit,saveMachine,adminMachine,AppError} from '../../../../lib/repository';
import {leadStatuses,settingsSchema} from '../../../../lib/validation';
import {originCheck,jsonBody,ok,failure} from '../../../../lib/http';
import {processOutbox,renderEmail} from '../../../../lib/communications';
import {commitImport} from '../../../../lib/imports';
type Context={params:Promise<{path:string[]}>};
export async function GET(request:Request,ctx:Context){try{const [resource,id]= (await ctx.params).path;const staff=await requireStaff();const db=await getDB();
 if(['leads','overview','logs'].includes(resource))await requireStaff(['ADMIN','SALES']);
 if(['machines','imports'].includes(resource))await requireStaff(['ADMIN','SALES']);
 if(['settings','users','audit'].includes(resource))await requireStaff(['ADMIN']);
 if(resource==='me')return ok(staff);
 if(resource==='imports'){await requireStaff(['ADMIN']);return ok((await db.query('SELECT id,committed,created_at FROM imports ORDER BY created_at DESC LIMIT 50')).rows);}
 if(resource==='overview'){const q=await db.query("SELECT (SELECT count(*)::int FROM machines WHERE status='AVAILABLE') AS available,(SELECT count(*)::int FROM leads WHERE status='NEW') AS new_leads,(SELECT count(*)::int FROM leads WHERE created_at>=current_date) AS today,(SELECT count(*)::int FROM outbox WHERE status IN ('FAILED','UNKNOWN','CONFIGURATION_REQUIRED')) AS failed");return ok(q.rows[0]);}
 if(resource==='machines')return ok(id?await adminMachine(db,id,staff.role):(await db.query('SELECT id,code,title_en,status,manufacturer,model,year,version FROM machines ORDER BY created_at DESC LIMIT 1000')).rows);
 if(resource==='leads'){if(!id)return ok((await db.query('SELECT id,type,status,name,company,country,email,created_at,assigned_to,snapshot FROM leads ORDER BY created_at DESC LIMIT 1000')).rows);const l=(await db.query('SELECT * FROM leads WHERE id=$1',[id])).rows[0];if(!l)throw new AppError('Lead not found',404);l.events=(await db.query('SELECT e.*,s.email AS actor_email FROM lead_events e LEFT JOIN staff s ON s.id=e.actor WHERE lead_id=$1 ORDER BY created_at',[id])).rows;l.deliveries=(await db.query('SELECT * FROM outbox WHERE lead_id=$1',[id])).rows;l.attachments=(await db.query('SELECT id,kind FROM media WHERE lead_id=$1',[id])).rows;if(l.machine_id)l.machine=await adminMachine(db,l.machine_id,staff.role);return ok(l);}
 if(resource==='logs')return ok((await db.query('SELECT o.*,l.name,l.email FROM outbox o JOIN leads l ON l.id=o.lead_id ORDER BY o.created_at DESC LIMIT 500')).rows);
 if(resource==='email-preview'){await requireStaff(['ADMIN','SALES']);const l=(await db.query('SELECT * FROM leads WHERE id=$1',[id])).rows[0];if(!l)throw new AppError('Lead not found',404);return ok(await renderEmail(db,l));}
 if(resource==='settings')return ok(await settings(db));
 if(resource==='taxonomy')return ok((await db.query('SELECT * FROM taxonomy ORDER BY kind,sort_order,name_en')).rows);
 if(resource==='content')return ok((await db.query('SELECT * FROM content ORDER BY kind,title_en')).rows);
 if(resource==='users')return ok((await db.query('SELECT * FROM staff ORDER BY email')).rows);
 if(resource==='assignees'){await requireStaff(['ADMIN','SALES']);return ok((await db.query("SELECT id,email FROM staff WHERE active=true AND role IN ('ADMIN','SALES')")).rows);}
 if(resource==='redirects')return ok((await db.query('SELECT * FROM redirects ORDER BY source')).rows);
 throw new AppError('Not found',404);
 }catch(e){return failure(e);}}
export async function POST(request:Request,ctx:Context){try{originCheck(request);const [resource,id]=(await ctx.params).path;const db=await getDB();const staff=await requireStaff();const data=await jsonBody(request);
 if(resource==='machines'){await requireStaff(['ADMIN']);return ok(await saveMachine(db,data,staff.id,id));}
 if(resource==='leads'){await requireStaff(['ADMIN','SALES']);const input=z.object({status:z.enum(leadStatuses),assigned_to:z.uuid().nullable(),note:z.string().trim().max(5000).default('')}).parse(data);await db.transaction(async tx=>{if(input.assigned_to&&!(await tx.query("SELECT id FROM staff WHERE id=$1 AND active=true AND role IN ('ADMIN','SALES')",[input.assigned_to])).rows.length)throw new AppError('Invalid assignee');const r=await tx.query('UPDATE leads SET status=$2,assigned_to=$3,updated_at=now() WHERE id=$1 RETURNING id',[id,input.status,input.assigned_to]);if(!r.rows.length)throw new AppError('Lead not found',404);await tx.query('INSERT INTO lead_events(lead_id,actor,text) VALUES($1,$2,$3)',[id,staff.id,`Status: ${input.status}. ${input.note}`]);await audit(tx,staff.id,'lead.updated',id);});return ok({ok:true});}
 if(resource==='settings'){await requireStaff(['ADMIN']);const s=settingsSchema.parse(data);await db.query('UPDATE settings SET data=$1 WHERE id=1',[JSON.stringify(s)]);await audit(db,staff.id,'settings.updated','1');return ok(s);}
 if(resource==='content'){await requireStaff(['ADMIN','MARKETING']);const c=z.object({slug:z.string().regex(/^[a-z0-9-]+$/),kind:z.enum(['page','service','article']),title_en:z.string().min(1).max(300),title_ar:z.string().min(1).max(300),body_en:z.string().max(100000),body_ar:z.string().max(100000),published:z.boolean(),arabic_ready:z.boolean(),seo_en:z.string().max(300).default(''),seo_ar:z.string().max(300).default('')}).parse(data);if(c.arabic_ready&&!c.body_ar.trim())throw new AppError('Arabic content is required.');await db.query('INSERT INTO content(slug,kind,title_en,title_ar,body_en,body_ar,published,arabic_ready,seo_en,seo_ar) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(slug) DO UPDATE SET title_en=$3,title_ar=$4,body_en=$5,body_ar=$6,published=$7,arabic_ready=$8,seo_en=$9,seo_ar=$10,updated_at=now()',[c.slug,c.kind,c.title_en,c.title_ar,c.body_en,c.body_ar,c.published,c.arabic_ready,c.seo_en,c.seo_ar]);await audit(db,staff.id,'content.updated',c.slug);return ok({ok:true});}
 if(resource==='taxonomy'){await requireStaff(['ADMIN']);const t=z.object({kind:z.enum(['category','manufacturer']),slug:z.string().regex(/^[a-z0-9-]+$/),name_en:z.string().min(1).max(100),name_ar:z.string().min(1).max(100),active:z.boolean().default(true),sort_order:z.coerce.number().int().default(0)}).parse(data);await db.query('INSERT INTO taxonomy(kind,slug,name_en,name_ar,active,sort_order) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(slug) DO UPDATE SET name_en=$3,name_ar=$4,active=$5,sort_order=$6',[t.kind,t.slug,t.name_en,t.name_ar,t.active,t.sort_order]);return ok({ok:true});}
 if(resource==='users'){await requireStaff(['ADMIN']);const u=z.object({id:z.uuid(),email:z.email(),role:z.enum(['ADMIN','SALES','MARKETING']),active:z.boolean()}).parse(data);if(u.id===staff.id&&(u.role!=='ADMIN'||!u.active))throw new AppError('Cannot remove your own administrator access.');await db.query('INSERT INTO staff(id,email,role,active) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET email=$2,role=$3,active=$4',[u.id,u.email,u.role,u.active]);await audit(db,staff.id,'staff.updated',u.id);return ok({ok:true});}
 if(resource==='redirects'){await requireStaff(['ADMIN','MARKETING']);const r=z.object({source:z.string().regex(/^\/[a-zA-Z0-9\-_/]+$/),destination:z.string().regex(/^\/[a-zA-Z0-9\-_/]+$/),enabled:z.boolean()}).parse(data);if(r.source===r.destination||r.source.startsWith('/admin')||r.source.startsWith('/api'))throw new AppError('Invalid redirect.');const chain=(await db.query('SELECT * FROM redirects WHERE enabled=true')).rows;let dest=r.destination;for(let i=0;i<=chain.length;i++){if(dest===r.source)throw new AppError('Redirect loop.');const next=chain.find(x=>x.source===dest);if(!next)break;dest=next.destination;}await db.query('INSERT INTO redirects(source,destination,enabled) VALUES($1,$2,$3) ON CONFLICT(source) DO UPDATE SET destination=$2,enabled=$3',[r.source,r.destination,r.enabled]);return ok({ok:true});}
 if(resource==='process'){await requireStaff(['ADMIN']);return ok(await processOutbox(db));}
 if(resource==='retry'){await requireStaff(['ADMIN']);if(!data.reconciled)throw new AppError('Confirm provider reconciliation before retry.');await db.query("UPDATE outbox SET status='PENDING',next_attempt=now(),error=NULL WHERE id=$1 AND status IN ('FAILED','UNKNOWN','CONFIGURATION_REQUIRED')",[id]);await audit(db,staff.id,'delivery.retry',id);return ok({ok:true});}
 if(resource==='imports'){await requireStaff(['ADMIN']);return ok(await commitImport(db,z.uuid().parse(id),staff.id));}
 throw new AppError('Not found',404);
 }catch(e){return failure(e);}}
