import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import sanitize from 'sanitize-html';
import {ArrowUpRight,Search,Globe2,ArrowRight,Settings2,Truck,Package} from 'lucide-react';
import {getDB,isLocal} from '../../lib/db';
import {catalog,settings,publicSettings} from '../../lib/repository';
import {words,href,type Locale} from '../../lib/i18n';
import {Shell,MachineCard,Empty,Title} from '../components/public-shell';
import {CatalogView} from '../components/catalog-view';
import {MachineView} from '../components/machine-view';
import {InquiryForm,TrackLink} from '../components/public-client';
export const dynamic='force-dynamic';
type Props={params:Promise<{path?:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
function route(path:string[]=[]){const locale:Locale=path[0]==='ar'?'ar':'en';return {locale,parts:locale==='ar'?path.slice(1):path};}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale,parts}=route((await params).path);const w=words[locale];let title=parts.length?w[parts[0] as keyof typeof w]||'RGM':locale==='ar'?'ماكينات طباعة مستعملة':'Used printing machinery';let description=locale==='ar'?'شراء وبيع وتوريد ماكينات الطباعة والتغليف المستعملة.':'Buy, sell and source used printing and packaging machinery.';let translated=true;try{const db=await getDB();if(parts[0]==='machines'&&parts[1]){const m=(await catalog(db,{},parts[1])).items[0];if(m){title=m['title_'+locale];description=m['seo_'+locale]||m['description_'+locale].slice(0,160);}}else if(parts.length){const c=(await db.query('SELECT * FROM content WHERE slug=$1 AND published=true',[parts.at(-1)])).rows[0];if(c){title=c['title_'+locale];description=c['seo_'+locale]||sanitize(c['body_'+locale],{allowedTags:[]}).slice(0,160);translated=c.arabic_ready;}}}catch{}const path=parts.length?'/'+parts.join('/'):'/';const base=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';return {title:title+' | Roza Graphic Machinery',description,robots:{index:process.env.APP_ENV==='production'&&(locale==='en'||translated),follow:true},alternates:{canonical:base+href(locale,path),languages:translated?{en:base+path,ar:base+href('ar',path)}:{en:base+path}},openGraph:{title:String(title),description,siteName:'Roza Graphic Machinery'}};}
export default async function PublicPage({params,searchParams}:Props){const {locale,parts}=route((await params).path);const w=words[locale];const db=await getDB();const cfg=await settings(db);const tax=(await db.query('SELECT * FROM taxonomy WHERE active=true ORDER BY sort_order,name_en')).rows;const query=Object.fromEntries(Object.entries(await searchParams).map(([k,v])=>[k,Array.isArray(v)?v[0]:v||'']));const section=parts[0]||'home';let body:React.ReactNode;const services=(await db.query("SELECT slug,title_en,title_ar,body_en,body_ar FROM content WHERE kind='service' AND published=true ORDER BY title_en")).rows;
 if(section==='home'){const home=(await db.query("SELECT * FROM content WHERE slug='home'")).rows[0];const stock=await catalog(db);body=<><section className="hero"><div className="hero-copy"><p className="eyebrow">RGM / {locale==='ar'?'ماكينات الطباعة والتغليف':'PRINTING & PACKAGING MACHINERY'}</p><h1>{home?.['title_'+locale]||w.machines}</h1><p>{home?.['body_'+locale]}</p><div className="actions"><Link className="button" href={href(locale,'/machines')}>{w.machines}<ArrowUpRight size={20}/></Link><Link className="text-link" href={href(locale,'/find-a-machine')}>{w.find}<ArrowRight size={18}/></Link></div></div><div className="hero-panel"><div className="hero-panel-top"><Globe2/><span>{locale==='ar'?'نصل إلى أسواق العالم':'CONNECTED TO GLOBAL MARKETS'}</span></div><div className="hero-word">RGM<span>Roza Graphic Machinery</span></div><div className="hero-markets"><span>{locale==='ar'?'السعودية · الإمارات · مصر':'SAUDI ARABIA · UAE · EGYPT'}</span><span>{locale==='ar'?'أفريقيا · أوروبا · العالم':'AFRICA · EUROPE · WORLDWIDE'}</span></div></div></section><section className="search-band"><div><p className="eyebrow">{locale==='ar'?'ابدأ بحثك':'FIND YOUR NEXT MACHINE'}</p><form action={href(locale,'/machines')} className="search-box"><Search/><input name="q" aria-label={w.search} placeholder={locale==='ar'?'الشركة المصنعة، الطراز، كود الماكينة…':'Manufacturer, model or machine code…'}/><button>{locale==='ar'?'بحث':'Search'}<ArrowRight size={18}/></button></form></div></section><section><div className="section-heading"><div><p className="eyebrow">{locale==='ar'?'المخزون':'OUR INVENTORY'}</p><h2>{w.latest}</h2></div><Link className="text-link" href={href(locale,'/machines')}>{w.all}<ArrowUpRight size={18}/></Link></div>{stock.items.length?<div className="machine-grid">{stock.items.slice(0,3).map(m=><MachineCard key={m.id} m={m} locale={locale}/>)}</div>:<Empty locale={locale}/>}</section><section className="service-section"><div className="section-heading"><div><p className="eyebrow">{locale==='ar'?'من الاختيار إلى التشغيل':'BEYOND THE MACHINE'}</p><h2>{locale==='ar'?'دعم فني في كل خطوة.':'Technical support at every step.'}</h2></div><Link href={href(locale,'/services')}>{w.services} ↗</Link></div><div className="service-grid">{services.slice(0,3).map((s,i)=><Link className="service-card" href={href(locale,'/services/'+s.slug)} key={s.slug}>{i===0?<Settings2/>:i===1?<Truck/>:<Package/>}<h3>{s['title_'+locale]}</h3><p>{s['body_'+locale]}</p><ArrowUpRight/></Link>)}</div></section><section className="sell-band"><div><p className="eyebrow">{locale==='ar'?'بيع ماكينتك':'SELL WITH RGM'}</p><h2>{locale==='ar'?'ماكينتك قد تكون ما يبحث عنه عميل آخر.':'Your next move starts here.'}</h2><p>{locale==='ar'?'أرسل بيانات الماكينة والصور إلى فريقنا لمراجعتها.':'Share your machine details and photos with our team for review.'}</p></div><Link className="button light" href={href(locale,'/sell-your-machine')}>{w.sell}<ArrowUpRight/></Link></section></>;}
 else if((section==='machines'&&!parts[1])||section==='categories'||(section==='brands'&&parts[1])){if(section==='categories')query.category=parts[1];if(section==='brands'){const b=tax.find(t=>t.slug===parts[1]&&t.kind==='manufacturer');if(!b)notFound();query.manufacturer=b.name_en;}body=<CatalogView locale={locale} query={query} tax={tax} result={await catalog(db,query)}/>;}
 else if(section==='machines'&&parts[1]){const m=(await catalog(db,{},parts[1])).items[0];if(!m)notFound();const related=(await catalog(db,{category:m.category})).items.filter(x=>x.id!==m.id).slice(0,3);body=<MachineView m={m} related={related} locale={locale} whatsapp={cfg.primary_whatsapp}/>;}
 else if(['find-a-machine','sell-your-machine','request-inspection','contact'].includes(section)){const type=({'find-a-machine':'MACHINE_WANTED','sell-your-machine':'SELL_MACHINE','request-inspection':'INSPECTION_REQUEST',contact:'GENERAL_CONTACT'} as Record<string,string>)[section];const title=({'find-a-machine':w.find,'sell-your-machine':w.sell,'request-inspection':w.inspection,contact:w.contact} as Record<string,string>)[section];body=<section><Title title={title}/><div className="request-layout"><aside><h2>{locale==='ar'?'دعنا نعرف ما تحتاجه.':'Tell us what you need.'}</h2><p>{locale==='ar'?'أرسل التفاصيل لفريقنا، وسنتواصل معك لمناقشة الخطوة التالية.':'Share the details with our team. We will get in touch to discuss the next step.'}</p>{cfg.general_email&&<p><TrackLink event="email_click" href={'mailto:'+cfg.general_email}>{cfg.general_email}</TrackLink></p>}{cfg.phone&&<p><TrackLink event="phone_click" href={'tel:'+cfg.phone}><bdi>{cfg.phone}</bdi></TrackLink></p>}{cfg.countries.map(c=><div key={c.country}><h3>{c.label}</h3><p>{c.address}</p><p><bdi>{c.phone}</bdi></p><p>{c.email}</p></div>)}</aside><InquiryForm locale={locale} type={type}/></div></section>;}
 else if(section==='services'&&!parts[1])body=<section><Title title={w.services}/><div className="service-grid">{services.map(s=><Link className="service-card" href={href(locale,'/services/'+s.slug)} key={s.slug}><Settings2/><h3>{s['title_'+locale]}</h3><p>{s['body_'+locale]}</p><ArrowUpRight/></Link>)}</div><Link className="button" href={href(locale,'/request-inspection')}>{w.inspection}</Link></section>;
 else if(section==='blog'){const posts=(await db.query("SELECT slug,title_en,title_ar,original_date,arabic_ready FROM content WHERE kind='article' AND published=true ORDER BY original_date DESC")).rows;body=<section><Title title={w.blog}/><div className="article-grid">{posts.map(p=><article key={p.slug}><p className="meta">{new Date(p.original_date).toLocaleDateString(locale)}</p><h2>{p['title_'+locale]}</h2><Link href={href(locale,'/'+p.slug)}>{w.read} ↗</Link></article>)}</div></section>;}
 else if(section==='brands'){const brands=(await db.query("SELECT DISTINCT t.slug,t.name_en,t.name_ar FROM taxonomy t JOIN machines m ON m.manufacturer=t.name_en WHERE t.kind='manufacturer' AND m.status='AVAILABLE'")).rows;body=<section><Title title={w.brands}/>{brands.length?<div className="service-grid">{brands.map(b=><Link className="service-card" key={b.slug} href={href(locale,'/brands/'+b.slug)}><h2>{b['name_'+locale]}</h2><ArrowUpRight/></Link>)}</div>:<Empty locale={locale}/>}</section>;}
 else {const c=(await db.query('SELECT * FROM content WHERE slug=$1 AND published=true',[parts.at(-1)])).rows[0];if(!c){if(['privacy','terms'].includes(section))body=<section><Title title={section==='privacy'?w.privacy:w.terms}/><p>{locale==='ar'?'المحتوى القانوني قيد الإعداد والمراجعة قبل الإطلاق. لا تُرسل بيانات حقيقية في نسخة الاختبار.':'Legal content is pending business review before launch. Do not submit real personal data in the test environment.'}</p></section>;else notFound();}else{const html=sanitize(c['body_'+locale]||(locale==='ar'&&!c.arabic_ready?c.body_en:''),{allowedTags:['p','h2','h3','h4','strong','em','br','ul','ol','li','blockquote','a','img'],allowedAttributes:{a:['href'],img:['src','alt']},allowedSchemes:['https','http']});body=<section className="content-page"><Title title={c['title_'+locale]}/>{locale==='ar'&&!c.arabic_ready&&<p className="notice-inline">{w.original}</p>}<div className="prose" dir={locale==='ar'&&!c.arabic_ready?'ltr':undefined} dangerouslySetInnerHTML={{__html:html}}/>{c.kind==='service'&&<div className="inquiry-panel"><h2>{locale==='ar'?'اطلب هذه الخدمة':'Request this service'}</h2><InquiryForm locale={locale} type="SERVICE_INQUIRY" service={c.slug}/></div>}{c.kind==='page'&&<Link className="button" href={href(locale,'/contact')}>{w.contact}<ArrowUpRight/></Link>}</section>;}}
 return <Shell locale={locale} config={publicSettings(cfg)} local={isLocal()}>{body}</Shell>;
}
